# Generated by Django 6.0.3 on 2026-04-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=100)),
                ('principal', models.FloatField()),
                ('interestRate', models.FloatField()),
                ('dueDate', models.DateField()),
            ],
            options={
                'db_table': 'scrd_banknote',
            },
        ),
    ]
