# Generated by Django 6.0.3 on 2026-04-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_bloodbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='unitsAvailable',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
