# Generated by Django 6.0.3 on 2026-04-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_bloodbank_unitsavailable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateLimitCode', models.CharField(max_length=100)),
                ('apiName', models.CharField(max_length=100)),
                ('limitPerMinute', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scrd_ratelimit',
            },
        ),
    ]
