# Generated by Django 6.0.3 on 2026-04-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_ratelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerName', models.CharField(max_length=100)),
                ('branchName', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scrd_branch',
            },
        ),
    ]
