# Generated by Django 6.0.3 on 2026-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemptCode', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('attemptTime', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scrd_attempt',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcastCode', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('sentBy', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scrd_broadcast',
            },
        ),
    ]
