# Generated by Django 6.0.3 on 2026-04-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0007_attempt_broadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('loginId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('confirmPassword', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('address', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('mobileNumber', models.CharField(default='', max_length=50)),
                ('roleId', models.IntegerField()),
                ('roleName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_user',
            },
        ),
        migrations.RenameField(
            model_name='broadcast',
            old_name='message',
            new_name='broadmessage',
        ),
    ]
