# Generated by Django 6.0.3 on 2026-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0008_user_rename_message_broadcast_broadmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchCode', models.CharField(max_length=100)),
                ('batchName', models.CharField(max_length=100)),
                ('totalRecords', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scrd_batchprocessing',
            },
        ),
        migrations.RenameField(
            model_name='broadcast',
            old_name='broadmessage',
            new_name='broadMessage',
        ),
    ]
