# Generated by Django 6.0.3 on 2026-05-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0009_batchprocessing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='spaceMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionName', models.CharField(max_length=100)),
                ('launchVehicle', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('missionStatus', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scrd_mission',
            },
        ),
    ]
