# Generated by Django 6.0.3 on 2026-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0010_spacemission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roleId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roleName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
