# Generated by Django 6.0.3 on 2026-05-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0011_alter_user_roleid_alter_user_rolename'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='scrd_User',
        ),
    ]
