# Generated by Django 6.0.3 on 2026-05-31 18:04

import CRUD.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0012_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentManagment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scrd_studentmanag',
            },
            bases=(CRUD.models.DropdownItem, models.Model),
        ),
    ]
