# Generated by Django 6.0.3 on 2026-05-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0013_studentmanagment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmanagment',
            name='course',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
