# Generated by Django 6.0.3 on 2026-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0014_studentmanagment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scrd_mobile',
            },
        ),
    ]
