# Generated by Django 6.0.3 on 2026-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0015_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateField(max_length=20)),
                ('status', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scrd_patientappointment',
            },
        ),
    ]
