# Generated by Django 6.0.3 on 2026-06-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0016_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='price',
        ),
    ]
